// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oihmekwnemzpfcgvtttx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9paG1la3duZW16cGZjZ3Z0dHR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMzExNTcsImV4cCI6MjA2MjcwNzE1N30.miTVlFbxDdvKUt0QbbFUJwoHoPvpp2ingGGHxwqS8VA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);