// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nvpyikozjuvxyfvjzima.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52cHlpa296anV2eHlmdmp6aW1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyOTUyNzksImV4cCI6MjA1Nzg3MTI3OX0.qeM43h6gEZsyiNMD-yh_7o57Z85dCw03WbCTvqYRsnY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);